kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "flask-sample-build" 
spec:
  runPolicy: "Serial" 
  source: 
    git:
      uri: "https://github.com/lysenkoivan/pyjwt_example"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent {
            node {
              label 'flask-sample-build' 
            }
          }
          options {
            timeout(time: 20, unit: 'MINUTES') 
          }
          stages {
            stage('test') {
              println('Test')
            }
          }
        }
    type: JenkinsPipeline
