kind: "HorizontalPodAutoscaler"
apiVersion: "autoscaling/v1"
metadata:
  name: pyjwt-app-auto-hpa
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: pyjwt-app-auto-dc
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
kind: Route
apiVersion: v1
metadata:
  name: pyjwt-app-auto-route
spec:
  to:
    kind: Service
    name: pyjwt-app-auto-svc
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: pyjwt-app-auto-svc
spec:
  selector:
    name: pyjwt-app-auto-dc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "pyjwt-app-auto-dc"
spec:
  template:
    metadata:
      labels:
        name: "pyjwt-app-auto-dc"
    spec:
      containers:
        - name: "pyjwt-app-auto"
          image: "enybor/pyjwt-example"
          ports:
            - containerPort: 5000
              protocol: "TCP"
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
  strategy:
    type: "Rolling"
