kind: "ImageStream"
apiVersion: "v1"
metadata:
  name: "s2i-pyjwt-app"
---
kind: "ImageStream"
apiVersion: "v1"
metadata:
  name: "python"
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "s2i-build"
spec:
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/enybor/pyjwt_example'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'python:3.7-alpine'
    type: Docker
  output:
    to:
      kind: "ImageStreamTag"
      name: "s2i-pyjwt-app:latest"


# todo not working yet
# todo can not create without existing ImageStream with specific tag